### ISSUE TITLE
Remove scmo folder after successful bam tagging

### ISSUE THREAD

**Issue by cgeisenberger** [BuysDB/SingleCellMultiOmics#145]
The temporary folder scmo is empty but not deleted after successful tagging

**Comment by BuysDB** [comment]
This is because when running multiple instances in the same folder we might run into interesting race conditions. It would be better to use the system's /tmp, but this is tricky as for example on the system we use we cannot use this location as it is very tiny. (It can be extended by setting an environment variable). I guess the best solution is to have a unique temporary folder for each run. I'll implement this.

**Comment by BuysDB** [comment]
The temp folder location can now be specified and defaults to the current directory. Every time the tool is run it gets a separate temp sub folder which gets removed upon successful finishing.
